services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: mytube
      POSTGRES_PASSWORD: mytube
      POSTGRES_DB: mytube
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: mytube
      MINIO_ROOT_PASSWORD: mytube123
    ports: ["9000:9000","9001:9001"]
    volumes: ["miniodata:/data"]

volumes:
  pgdata:
  miniodata:
